apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxpilot-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nachikethareddyg/fluxpilot-gitops-controller
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxpilot-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxpilot-repo
